In [2]:
#program to illustrate multiclass logistic regression
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
class LogReg:
    def __init__(self,alph,maxitr):
        self.alph=alph
        self.maxitr=maxitr
        
    #conversion of label values for the objective of multiclass logistic regression
    def convert(self,y,rowcnt,nclass): 
        y1=np.zeros((rowcnt,nclass))
        for i in range(0,nclass):
            for j in range(0,rowcnt):
                if y[j]==np.unique(y)[i]:
                    y1[j,i]=1
                else:
                    y1[j,i]=0
        return y1       
        
    #to calculate the predicted values of labels based on weights and independent variables 
    def predict(self,x): 
        ypred=np.zeros((x.shape[0],self.w.shape[1]))
        for i in range(0,self.w.shape[1]) :
            weight=self.w[:,i]
            h=weight[0]
            for j in range(1,colcnt):
                h+=weight[j]*x[:,j-1] 
            ypred[:,i]=h   
        return 1/(1+np.exp(-ypred))
    
    
    
    #to train the model. Starting with initial weights for each class of multiclass logistic regression, it calculates 
    #the initial predicted values of labels and corresponding error for all the classes. 
    #Gradient descent is performed over 'maxitr' number of iterations to find the new weights for each class.
    #We fix the optimum value of 'maxitr' by running the model by various trials.
    #We also assume the learning rate 'alph' at optimum level
    def fitting(self,x,y1,colcnt,nclass):
        self.w=np.zeros((colcnt,nclass))
        print("Initial Weights=",self.w)
        ypred=self.predict(x)
        print("Initial predicted values of y=")
        err=y1-ypred
        print(ypred)
        print(err)
        for i in range(0,maxitr):
            for j in range(0,nclass):
                self.w[0,j]+=(alph/rowcnt)*np.sum(err[:,j])
                for k in range(1,colcnt):
                    self.w[k,j]+=(alph/rowcnt)*np.sum(x[:,k-1]*err[:,j])
            print("Calculated weights=")
            print(self.w)
            ypred=self.predict(x)
            print("Predicted values of y=")
            print(ypred)
            err=y1-ypred  
            print("Error=")
            print(err)
        print("Accuracy of train=",self.accuracy(y1,ypred)*100)
    #to test the accuracy of the predicted result
    def accuracy(self,y,ypred): 
        match=0
        for i in range(0,y.shape[1]):
            for j in range(0,y.shape[0]):
                if(y[j,i]==1 and ypred[j,i]>=0.5):
                    match+=1
        match=match/y.shape[0]
        return match
    
     
df=pd.read_csv('pythonlab\mnist_train_small.csv')
alph=0.01
maxitr=100
nitr=0
rowcnt=len(df.index) #calculating the number of rows in the dataframe
colcnt=len(df.columns)#calculating the number of columns in the dataframe
x=(1/255)*np.array(df.iloc[:,1:colcnt])#normalizing the X values as X=(X-min)/(max-min)
y=np.array(df.iloc[:,0])
print(y)
nclass=len(np.unique(y)) #calculating the number of different classes present in y
#print(nclass)
#print(np.unique(y))
p=LogReg(alph,maxitr)
y1=p.convert(y,rowcnt,nclass)
print(y1)     
print("Number of rows=",rowcnt," Number of columns=",colcnt)
p.fitting(x,y1,colcnt,nclass)  


testdf=pd.read_csv('pythonlab\mnist_test.csv')
rowcnttest=len(testdf.index)
x2=(1/255)*np.array(testdf.iloc[:,1:colcnt])#normalizing the X values as X=(X-min)/(max-min)
y2=np.array(testdf.iloc[:,0])
nclass2=len(np.unique(y2))
y3=p.convert(y2,rowcnttest,nclass2)
ypred2=p.predict(x2)
print("Predicted values of y in test data")
print(ypred2)
#print(y3)
acc=p.accuracy(y3,ypred2)
print("Accuracy= ",acc*100,"%")

[6 5 7 ... 2 9 5]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
Number of rows= 20000  Number of columns= 785
Initial Weights= [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Initial predicted values of y=
[[0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 ...
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]]
[[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 ...  0.5 -0.5 -0.5]
 ...
 [-0.5 -0.5  0.5 ... -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 ... -0.5 -0.5  0.5]
 [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]
Calculated weights=
[[-0.004019  -0.0038785 -0.0040055 ... -0.003937  -0.0040445 -0.003988 ]
 [ 0.         0.         0.        ...  0.         0.         0

Predicted values of y=
[[0.36475384 0.34060435 0.36110774 ... 0.34743123 0.35374052 0.34705259]
 [0.36469548 0.33376785 0.34565904 ... 0.34386918 0.35662643 0.34758717]
 [0.37398521 0.32984053 0.34070666 ... 0.35786192 0.3485153  0.35589753]
 ...
 [0.32809218 0.29549814 0.32310653 ... 0.30580232 0.31412346 0.30673965]
 [0.3450886  0.33858113 0.34500041 ... 0.35169027 0.35333757 0.35286623]
 [0.35703882 0.33212009 0.34650204 ... 0.33434192 0.35079734 0.34115522]]
Error=
[[-0.36475384 -0.34060435 -0.36110774 ... -0.34743123 -0.35374052
  -0.34705259]
 [-0.36469548 -0.33376785 -0.34565904 ... -0.34386918 -0.35662643
  -0.34758717]
 [-0.37398521 -0.32984053 -0.34070666 ...  0.64213808 -0.3485153
  -0.35589753]
 ...
 [-0.32809218 -0.29549814  0.67689347 ... -0.30580232 -0.31412346
  -0.30673965]
 [-0.3450886  -0.33858113 -0.34500041 ... -0.35169027 -0.35333757
   0.64713377]
 [-0.35703882 -0.33212009 -0.34650204 ... -0.33434192 -0.35079734
  -0.34115522]]
Calculated weights=
[[-0.02203035 -

Predicted values of y=
[[0.29668468 0.2588582  0.29113313 ... 0.26856375 0.27783647 0.26730031]
 [0.2971992  0.24815403 0.26510801 ... 0.26322598 0.28351282 0.26892745]
 [0.31380882 0.24174692 0.25673739 ... 0.287138   0.26944239 0.2830717 ]
 ...
 [0.24749575 0.2000184  0.24040057 ... 0.21391096 0.2252235  0.21468608]
 [0.26398594 0.25636911 0.2644912  ... 0.27693857 0.27819013 0.27838698]
 [0.28531822 0.24690649 0.26802886 ... 0.24876722 0.27491616 0.25957191]]
Error=
[[-0.29668468 -0.2588582  -0.29113313 ... -0.26856375 -0.27783647
  -0.26730031]
 [-0.2971992  -0.24815403 -0.26510801 ... -0.26322598 -0.28351282
  -0.26892745]
 [-0.31380882 -0.24174692 -0.25673739 ...  0.712862   -0.26944239
  -0.2830717 ]
 ...
 [-0.24749575 -0.2000184   0.75959943 ... -0.21391096 -0.2252235
  -0.21468608]
 [-0.26398594 -0.25636911 -0.2644912  ... -0.27693857 -0.27819013
   0.72161302]
 [-0.28531822 -0.24690649 -0.26802886 ... -0.24876722 -0.27491616
  -0.25957191]]
Calculated weights=
[[-0.03362968 -

Predicted values of y=
[[0.25931967 0.21199667 0.25251589 ... 0.22329027 0.23437925 0.2211959 ]
 [0.26052026 0.19886761 0.21852803 ... 0.21690883 0.24249622 0.22390088]
 [0.28344816 0.19087012 0.20772922 ... 0.24840109 0.22380328 0.24246874]
 ...
 [0.20615289 0.15010305 0.19789594 ... 0.16552267 0.17821763 0.16601039]
 [0.21717992 0.20962774 0.21829635 ... 0.23535341 0.23586256 0.23687674]
 [0.24592344 0.1985583  0.22368494 ... 0.19967858 0.23242695 0.21313127]]
Error=
[[-0.25931967 -0.21199667 -0.25251589 ... -0.22329027 -0.23437925
  -0.2211959 ]
 [-0.26052026 -0.19886761 -0.21852803 ... -0.21690883 -0.24249622
  -0.22390088]
 [-0.28344816 -0.19087012 -0.20772922 ...  0.75159891 -0.22380328
  -0.24246874]
 ...
 [-0.20615289 -0.15010305  0.80210406 ... -0.16552267 -0.17821763
  -0.16601039]
 [-0.21717992 -0.20962774 -0.21829635 ... -0.23535341 -0.23586256
   0.76312326]
 [-0.24592344 -0.1985583  -0.22368494 ... -0.19967858 -0.23242695
  -0.21313127]]
Calculated weights=
[[-0.04189968 

Predicted values of y=
[[0.23715803 0.18215094 0.22941807 ... 0.19455898 0.20703219 0.19173709]
 [0.2390403  0.16727845 0.1887269  ... 0.18742843 0.21733914 0.19541557]
 [0.26792008 0.15817417 0.17605283 ... 0.22533028 0.19472397 0.21770062]
 ...
 [0.18293037 0.12051006 0.1738661  ... 0.13682168 0.15042374 0.1370563 ]
 [0.18734018 0.18009598 0.18902652 ... 0.20999992 0.20975291 0.21156926]
 [0.22235984 0.16798261 0.19603859 ... 0.16839362 0.20632378 0.18385693]]
Error=
[[-0.23715803 -0.18215094 -0.22941807 ... -0.19455898 -0.20703219
  -0.19173709]
 [-0.2390403  -0.16727845 -0.1887269  ... -0.18742843 -0.21733914
  -0.19541557]
 [-0.26792008 -0.15817417 -0.17605283 ...  0.77466972 -0.19472397
  -0.21770062]
 ...
 [-0.18293037 -0.12051006  0.8261339  ... -0.13682168 -0.15042374
  -0.1370563 ]
 [-0.18734018 -0.18009598 -0.18902652 ... -0.20999992 -0.20975291
   0.78843074]
 [-0.22235984 -0.16798261 -0.19603859 ... -0.16839362 -0.20632378
  -0.18385693]]
Calculated weights=
[[-0.04823414 

Predicted values of y=
[[0.22337972 0.16163503 0.21492386 ... 0.1749377  0.18859885 0.17146713]
 [0.22592137 0.14538079 0.1681649  ... 0.1671908  0.20094098 0.17602503]
 [0.26068643 0.13545332 0.15394599 ... 0.2108936  0.17478135 0.20165707]
 ...
 [0.16916478 0.10124945 0.15948861 ... 0.11822228 0.13257544 0.11824588]
 [0.16681586 0.15994828 0.16905732 ... 0.19355723 0.19258412 0.19518154]
 [0.20743948 0.14705043 0.17751886 ... 0.14682682 0.18920755 0.16395899]]
Error=
[[-0.22337972 -0.16163503 -0.21492386 ... -0.1749377  -0.18859885
  -0.17146713]
 [-0.22592137 -0.14538079 -0.1681649  ... -0.1671908  -0.20094098
  -0.17602503]
 [-0.26068643 -0.13545332 -0.15394599 ...  0.7891064  -0.17478135
  -0.20165707]
 ...
 [-0.16916478 -0.10124945  0.84051139 ... -0.11822228 -0.13257544
  -0.11824588]
 [-0.16681586 -0.15994828 -0.16905732 ... -0.19355723 -0.19258412
   0.80481846]
 [-0.20743948 -0.14705043 -0.17751886 ... -0.14682682 -0.18920755
  -0.16395899]]
Calculated weights=
[[-0.05333983 

Predicted values of y=
[[0.21461833 0.14672424 0.20564324 ... 0.1607955  0.17554097 0.15673122]
 [0.2177992  0.12930358 0.15315202 ... 0.15249957 0.1898258  0.16209622]
 [0.25852166 0.11873444 0.13760431 ... 0.20167315 0.16033471 0.19087093]
 ...
 [0.16083971 0.08782759 0.15070949 ... 0.10536256 0.12041361 0.10520698]
 [0.15185621 0.14540832 0.15466231 ... 0.18246813 0.18079423 0.18416597]
 [0.19764978 0.1318623  0.16444686 ... 0.13106476 0.17747702 0.1496608 ]]
Error=
[[-0.21461833 -0.14672424 -0.20564324 ... -0.1607955  -0.17554097
  -0.15673122]
 [-0.2177992  -0.12930358 -0.15315202 ... -0.15249957 -0.1898258
  -0.16209622]
 [-0.25852166 -0.11873444 -0.13760431 ...  0.79832685 -0.16033471
  -0.19087093]
 ...
 [-0.16083971 -0.08782759  0.84929051 ... -0.10536256 -0.12041361
  -0.10520698]
 [-0.15185621 -0.14540832 -0.15466231 ... -0.18246813 -0.18079423
   0.81583403]
 [-0.19764978 -0.1318623  -0.16444686 ... -0.13106476 -0.17747702
  -0.1496608 ]]
Calculated weights=
[[-0.05761672 -

Predicted values of y=
[[0.20903476 0.1354193  0.19973803 ... 0.15017312 0.16594167 0.1455542 ]
 [0.21283931 0.11697413 0.14169784 ... 0.14136678 0.18211472 0.15167185]
 [0.25965105 0.10588878 0.12497535 ... 0.19582589 0.14941728 0.18347111]
 ...
 [0.1558722  0.07797962 0.14544716 ... 0.09602525 0.11175767 0.09571349]
 [0.1404398  0.13445726 0.14383465 ... 0.17481898 0.1724603  0.17661208]
 [0.1910906  0.1203441  0.15484799 ... 0.11901568 0.16919638 0.13894008]]
Error=
[[-0.20903476 -0.1354193  -0.19973803 ... -0.15017312 -0.16594167
  -0.1455542 ]
 [-0.21283931 -0.11697413 -0.14169784 ... -0.14136678 -0.18211472
  -0.15167185]
 [-0.25965105 -0.10588878 -0.12497535 ...  0.80417411 -0.14941728
  -0.18347111]
 ...
 [-0.1558722  -0.07797962  0.85455284 ... -0.09602525 -0.11175767
  -0.09571349]
 [-0.1404398  -0.13445726 -0.14383465 ... -0.17481898 -0.1724603
   0.82338792]
 [-0.1910906  -0.1203441  -0.15484799 ... -0.11901568 -0.16919638
  -0.13894008]]
Calculated weights=
[[-0.06131049 -

Predicted values of y=
[[0.20553936 0.12655773 0.19612774 ... 0.14192705 0.15867917 0.13678277]
 [0.20995559 0.10719016 0.13264258 ... 0.13263567 0.17670872 0.1436113 ]
 [0.26300634 0.09568117 0.11486402 ... 0.19227241 0.14088167 0.17836324]
 ...
 [0.15307885 0.07045678 0.14253285 ... 0.08897956 0.1053903  0.08852873]
 [0.13139208 0.12592541 0.13540664 ... 0.1694935  0.16645975 0.17140546]
 [0.18664716 0.11129945 0.14757511 ... 0.10947002 0.16323924 0.13062509]]
Error=
[[-0.20553936 -0.12655773 -0.19612774 ... -0.14192705 -0.15867917
  -0.13678277]
 [-0.20995559 -0.10719016 -0.13264258 ... -0.13263567 -0.17670872
  -0.1436113 ]
 [-0.26300634 -0.09568117 -0.11486402 ...  0.80772759 -0.14088167
  -0.17836324]
 ...
 [-0.15307885 -0.07045678  0.85746715 ... -0.08897956 -0.1053903
  -0.08852873]
 [-0.13139208 -0.12592541 -0.13540664 ... -0.1694935  -0.16645975
   0.82859454]
 [-0.18664716 -0.11129945 -0.14757511 ... -0.10947002 -0.16323924
  -0.13062509]]
Calculated weights=
[[-0.06458139 -

Predicted values of y=
[[0.20344404 0.11941982 0.19413486 ... 0.13534739 0.1530557  0.12970125]
 [0.2084621  0.09920922 0.12526822 ... 0.12559022 0.17292345 0.13720755]
 [0.26789591 0.08734862 0.10653126 ... 0.19033742 0.13401671 0.17486502]
 ...
 [0.15173632 0.06452037 0.14126133 ... 0.08349314 0.10058373 0.08291677]
 [0.12398932 0.1190909  0.12865609 ... 0.16579721 0.16209518 0.16785347]
 [0.18362259 0.10399299 0.14191874 ... 0.10168367 0.15890765 0.12399333]]
Error=
[[-0.20344404 -0.11941982 -0.19413486 ... -0.13534739 -0.1530557
  -0.12970125]
 [-0.2084621  -0.09920922 -0.12526822 ... -0.12559022 -0.17292345
  -0.13720755]
 [-0.26789591 -0.08734862 -0.10653126 ...  0.80966258 -0.13401671
  -0.17486502]
 ...
 [-0.15173632 -0.06452037  0.85873867 ... -0.08349314 -0.10058373
  -0.08291677]
 [-0.12398932 -0.1190909  -0.12865609 ... -0.16579721 -0.16209518
   0.83214653]
 [-0.18362259 -0.10399299 -0.14191874 ... -0.10168367 -0.15890765
  -0.12399333]]
Calculated weights=
[[-0.06753861 -

Predicted values of y=
[[0.20229251 0.11353724 0.19331167 ... 0.1299713  0.14861569 0.12384355]
 [0.20790354 0.09254933 0.11910835 ... 0.11976497 0.1703108  0.13200025]
 [0.27384539 0.08039565 0.09949772 ... 0.18957513 0.12835991 0.17252863]
 ...
 [0.15137604 0.05970825 0.14118111 ... 0.07910548 0.09687833 0.07841502]
 [0.11776483 0.11348532 0.12311408 ... 0.16327505 0.15891124 0.16550301]
 [0.18155952 0.09794925 0.13741767 ... 0.09517578 0.15574682 0.1185767 ]]
Error=
[[-0.20229251 -0.11353724 -0.19331167 ... -0.1299713  -0.14861569
  -0.12384355]
 [-0.20790354 -0.09254933 -0.11910835 ... -0.11976497 -0.1703108
  -0.13200025]
 [-0.27384539 -0.08039565 -0.09949772 ...  0.81042487 -0.12835991
  -0.17252863]
 ...
 [-0.15137604 -0.05970825  0.85881889 ... -0.07910548 -0.09687833
  -0.07841502]
 [-0.11776483 -0.11348532 -0.12311408 ... -0.16327505 -0.15891124
   0.83449699]
 [-0.18155952 -0.09794925 -0.13741767 ... -0.09517578 -0.15574682
  -0.1185767 ]]
Calculated weights=
[[-0.07025887 -

Predicted values of y=
[[0.20177102 0.10859273 0.19334927 ... 0.1254849  0.14504977 0.11889407]
 [0.20796648 0.08688473 0.11384815 ... 0.11484518 0.16856519 0.12767761]
 [0.28051504 0.0744872  0.09344027 ... 0.18967801 0.1235986  0.17104757]
 ...
 [0.1516806  0.05571795 0.14198854 ... 0.07551385 0.09397066 0.07471954]
 [0.11240687 0.10879215 0.11846403 ... 0.1616159  0.15659836 0.16404504]
 [0.18014678 0.09284803 0.13375988 ... 0.08962309 0.15344805 0.11405957]]
Error=
[[-0.20177102 -0.10859273 -0.19334927 ... -0.1254849  -0.14504977
  -0.11889407]
 [-0.20796648 -0.08688473 -0.11384815 ... -0.11484518 -0.16856519
  -0.12767761]
 [-0.28051504 -0.0744872  -0.09344027 ...  0.81032199 -0.1235986
  -0.17104757]
 ...
 [-0.1516806  -0.05571795  0.85801146 ... -0.07551385 -0.09397066
  -0.07471954]
 [-0.11240687 -0.10879215 -0.11846403 ... -0.1616159  -0.15659836
   0.83595496]
 [-0.18014678 -0.09284803 -0.13375988 ... -0.08962309 -0.15344805
  -0.11405957]]
Calculated weights=
[[-0.07279731 -

Predicted values of y=
[[0.20165844 0.10436421 0.19402683 ... 0.12166845 0.14214113 0.11463227]
 [0.20842964 0.08198783 0.10926846 ... 0.11061117 0.16747116 0.12402156]
 [0.28765414 0.06938892 0.08813415 ... 0.19042597 0.1195147  0.17020479]
 ...
 [0.15242779 0.05234404 0.1434706  ... 0.07251188 0.09165301 0.07162331]
 [0.10770146 0.10479032 0.11448538 ... 0.16059955 0.15493903 0.16326143]
 [0.17916729 0.08846639 0.1307273  ... 0.08480111 0.15179473 0.1102221 ]]
Error=
[[-0.20165844 -0.10436421 -0.19402683 ... -0.12166845 -0.14214113
  -0.11463227]
 [-0.20842964 -0.08198783 -0.10926846 ... -0.11061117 -0.16747116
  -0.12402156]
 [-0.28765414 -0.06938892 -0.08813415 ...  0.80957403 -0.1195147
  -0.17020479]
 ...
 [-0.15242779 -0.05234404  0.8565294  ... -0.07251188 -0.09165301
  -0.07162331]
 [-0.10770146 -0.10479032 -0.11448538 ... -0.16059955 -0.15493903
   0.83673857]
 [-0.17916729 -0.08846639 -0.1307273  ... -0.08480111 -0.15179473
  -0.1102221 ]]
Calculated weights=
[[-0.07519415 -

Predicted values of y=
[[0.20179662 0.10069192 0.19518182 ... 0.11836412 0.13973382 0.11090006]
 [0.20913455 0.07769519 0.10521284 ... 0.10690557 0.16687259 0.12087554]
 [0.29507432 0.06493229 0.08341896 ... 0.19165674 0.11595214 0.16984212]
 ...
 [0.15345864 0.04944267 0.14547243 ... 0.0699547  0.08977889 0.06898113]
 [0.10349857 0.10132125 0.11102046 ... 0.16006561 0.15377624 0.16299378]
 [0.17846737 0.08464474 0.12816358 ... 0.08054979 0.15063064 0.10690708]]
Error=
[[-0.20179662 -0.10069192 -0.19518182 ... -0.11836412 -0.13973382
  -0.11090006]
 [-0.20913455 -0.07769519 -0.10521284 ... -0.10690557 -0.16687259
  -0.12087554]
 [-0.29507432 -0.06493229 -0.08341896 ...  0.80834326 -0.11595214
  -0.16984212]
 ...
 [-0.15345864 -0.04944267  0.85452757 ... -0.0699547  -0.08977889
  -0.06898113]
 [-0.10349857 -0.10132125 -0.11102046 ... -0.16006561 -0.15377624
   0.83700622]
 [-0.17846737 -0.08464474 -0.12816358 ... -0.08054979 -0.15063064
  -0.10690708]]
Calculated weights=
[[-0.07747903 

Predicted values of y=
[[0.20207184 0.09745838 0.1966917  ... 0.11545614 0.13771324 0.10758169]
 [0.20996712 0.07388668 0.10156738 ... 0.10361327 0.16665378 0.11812476]
 [0.30263301 0.06099313 0.07917768 ... 0.19324766 0.11279686 0.16984165]
 ...
 [0.15465806 0.04691051 0.14787799 ... 0.06773813 0.08824248 0.06668864]
 [0.09969122 0.09826856 0.10795422 ... 0.15989455 0.15299411 0.16312434]
 [0.17793752 0.08126621 0.12595423 ... 0.07675245 0.1498406  0.10399955]]
Error=
[[-0.20207184 -0.09745838 -0.1966917  ... -0.11545614 -0.13771324
  -0.10758169]
 [-0.20996712 -0.07388668 -0.10156738 ... -0.10361327 -0.16665378
  -0.11812476]
 [-0.30263301 -0.06099313 -0.07917768 ...  0.80675234 -0.11279686
  -0.16984165]
 ...
 [-0.15465806 -0.04691051  0.85212201 ... -0.06773813 -0.08824248
  -0.06668864]
 [-0.09969122 -0.09826856 -0.10795422 ... -0.15989455 -0.15299411
   0.83687566]
 [-0.17793752 -0.08126621 -0.12595423 ... -0.07675245 -0.1498406
  -0.10399955]]
Calculated weights=
[[-0.07967392 -

Predicted values of y=
[[0.20240262 0.09457549 0.19846233 ... 0.11285819 0.13599376 0.10459091]
 [0.21084552 0.07047222 0.09824773 ... 0.10064861 0.16672741 0.11568355]
 [0.3102224  0.05747804 0.07532338 ... 0.19510425 0.10996406 0.17011381]
 ...
 [0.15594249 0.04467167 0.15059809 ... 0.06578578 0.08696575 0.0646693 ]
 [0.09620209 0.09554528 0.10520128 ... 0.1599956  0.15250553 0.1635639 ]
 [0.1774999  0.07824352 0.12401408 ... 0.07332242 0.14933809 0.10141397]]
Error=
[[-0.20240262 -0.09457549 -0.19846233 ... -0.11285819 -0.13599376
  -0.10459091]
 [-0.21084552 -0.07047222 -0.09824773 ... -0.10064861 -0.16672741
  -0.11568355]
 [-0.3102224  -0.05747804 -0.07532338 ...  0.80489575 -0.10996406
  -0.17011381]
 ...
 [-0.15594249 -0.04467167  0.84940191 ... -0.06578578 -0.08696575
  -0.0646693 ]
 [-0.09620209 -0.09554528 -0.10520128 ... -0.1599956  -0.15250553
   0.8364361 ]
 [-0.1774999  -0.07824352 -0.12401408 ... -0.07332242 -0.14933809
  -0.10141397]]
Calculated weights=
[[-0.08179515 

Predicted values of y=
[[0.20273126 0.09197619 0.20042032 ... 0.11050501 0.13451044 0.1018626 ]
 [0.21171179 0.0673831  0.09519064 ... 0.09794695 0.16702655 0.11348707]
 [0.31776176 0.0543155  0.07179043 ... 0.1971526  0.10738976 0.17058955]
 ...
 [0.15725161 0.04266942 0.15356275 ... 0.06404073 0.08589022 0.06286606]
 [0.09297461 0.09308544 0.10269741 ... 0.16029887 0.15224409 0.16424376]
 [0.17709977 0.07551042 0.12227895 ... 0.07019431 0.14905715 0.0990857 ]]
Error=
[[-0.20273126 -0.09197619 -0.20042032 ... -0.11050501 -0.13451044
  -0.1018626 ]
 [-0.21171179 -0.0673831  -0.09519064 ... -0.09794695 -0.16702655
  -0.11348707]
 [-0.31776176 -0.0543155  -0.07179043 ...  0.8028474  -0.10738976
  -0.17058955]
 ...
 [-0.15725161 -0.04266942  0.84643725 ... -0.06404073 -0.08589022
  -0.06286606]
 [-0.09297461 -0.09308544 -0.10269741 ... -0.16029887 -0.15224409
   0.83575624]
 [-0.17709977 -0.07551042 -0.12227895 ... -0.07019431 -0.14905715
  -0.0990857 ]]
Calculated weights=
[[-0.0838549  