In [13]:
#program to implement neural network algorithm
import numpy as np
import pandas as pd

class smallneur:
    
    #calculates the value of the sigmoid activation function
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    #calculates the value of the derivative of the sigmoid function
    def sig_der(self,x):
        return self.sigmoid(x)*(1-self.sigmoid(x))
    
    #calculates the value of the softmax activation function
    def softmax(self,x):
        ex = np.exp(x)
        return ex / ex.sum(axis=1, keepdims=True)
    
    #this method uses the sigmoid function and softmax function to calculate the activation values at hidden layer and output 
    #layer respectively. We are using 1 hidden layer consisting of 10 nodes. The cross entropy cost function has been used.
    # In the backpropagation the derivatives are calculated in 2 phases i.e output layer followed by hidden layer.
    #Hence the improved weights are calculated and this has been repeated over maxitr number of times.
    def fitting(self,x,y):
        #forpropagation
        rowcnt=x.shape[0]
        colcnt=x.shape[1]
        hidnode=100
        out_labels=10
        self.Wh=np.random.rand(colcnt,hidnode)
        self.bh=np.random.randn(hidnode)
        self.Wo=np.random.rand(hidnode,out_labels)
        self.bo=np.random.randn(out_labels)
    
        y1 = np.zeros((rowcnt, out_labels))
        for i in range(rowcnt):
            y1[i, y[i]] = 1
        
        flag=False
        nitr=0
        for nitr in range(maxitr):
            nitr+=1
            print('')
            print("Running Iteration number=",nitr)
            
            #phase 1
            zh=np.dot(x,self.Wh)+self.bh
            ah=self.sigmoid(zh)
            #phase 2
            zo=np.dot(ah,self.Wo)+self.bo
            ao=self.softmax(zo)
            (zo)
            print("Predicted values of y:")
            print(ao)
            
            #backpropagation
            
            #Phase 1
            outerr = ao - y1
            weight_err= ah
            dcost_wo = np.dot(weight_err.T, outerr)
            dcost_bo = outerr
            
            #Phase 2
            dzo_dah = self.Wo
            dcost_dah = np.dot(outerr , dzo_dah.T)
            dah_dzh = self.sig_der(zh)
            dzh_dwh = x
            dcost_wh = np.dot(dzh_dwh.T, dah_dzh * dcost_dah)
            dcost_bh = dcost_dah * dah_dzh
            
            #Updation         
            self.Wh-=alph*dcost_wh
            self.bh-=alph*dcost_bh.sum(axis=0)
            self.Wo-=alph*dcost_wo
            self.bo-=alph*dcost_bo.sum(axis=0)
            
            C=-np.sum(y1*np.log(ao))
            print("Loss function=",C)
            
            
        print("label values=")
        print(y1)
        print("Final predicted values=")
        print(ao)
        print("Accuracy of train=",self.accuracy(y1,ao)*100,"%")    
        
    #to calculate the predicted values of labels using weights and independent variables        
    def predict(self,x):
        zh=np.dot(x,self.Wh)+self.bh
        ah=self.sigmoid(zh)
       
        zo=np.dot(ah,self.Wo)+self.bo
        ao=self.softmax(zo)
        return ao
    
    #to calculate the accuracy of the model    
    def accuracy(self,y,ypred): 
        match=0
        for i in range(0,y.shape[1]):
            for j in range(0,y.shape[0]):
                
                if(y[j,i]==1 and ypred[j,i]>=0.5):
                    match+=1
        match=match/y.shape[0]
        return match
#training the model        
df=pd.read_csv('pythonlab\mnist_train_small.csv')
alph=0.0001
maxitr=100
thres=0.001
#nitr=0
rowcnt=len(df.index)
colcnt=len(df.columns)
x=(1/255)*np.array(df.iloc[:,1:colcnt])#normalizing the X values as X=(X-min)/(max-min)
#x=np.transpose(x)
y=np.array(df.iloc[:,0])
print("Number of rows=",rowcnt," Number of columns=",colcnt)
p=smallneur()
p.fitting(x,y)

#testing 
testdf=pd.read_csv('pythonlab\mnist_test.csv')
x2=(1/255)*np.array(testdf.iloc[:,1:colcnt])
y2=np.array(testdf.iloc[:,0])
y3= np.zeros((x2.shape[0], 10))
for i in range(x2.shape[0]):
        y3[i, y2[i]] = 1       
ypred2=p.predict(x2) 
print("Actual values of y=")
print(y3)
print("Predicted values of y in test:")
print(ypred2)
print("Accuracy of test=",p.accuracy(y3,ypred2)*100,"%")




Number of rows= 20000  Number of columns= 785

Running Iteration number= 1
Predicted values of y:
[[0.75965417 0.00127919 0.02050655 ... 0.00088314 0.01511144 0.00760604]
 [0.75965417 0.00127919 0.02050655 ... 0.00088314 0.01511144 0.00760604]
 [0.75965417 0.00127919 0.02050655 ... 0.00088314 0.01511144 0.00760604]
 ...
 [0.75965417 0.00127919 0.02050655 ... 0.00088314 0.01511144 0.00760604]
 [0.75965417 0.00127919 0.02050655 ... 0.00088314 0.01511144 0.00760604]
 [0.75965417 0.00127919 0.02050655 ... 0.00088314 0.01511144 0.00760604]]
Loss function= 120798.03752220335

Running Iteration number= 2
Predicted values of y:
[[6.84795419e-66 6.68002608e-01 1.69367745e-02 ... 1.53254814e-01
  1.68813116e-02 1.21157193e-01]
 [6.84795419e-66 6.68002608e-01 1.69367745e-02 ... 1.53254814e-01
  1.68813116e-02 1.21157193e-01]
 [6.84795419e-66 6.68002608e-01 1.69367745e-02 ... 1.53254814e-01
  1.68813116e-02 1.21157193e-01]
 ...
 [6.84795419e-66 6.68002608e-01 1.69367745e-02 ... 1.53254814e-01
  1.

Loss function= 1823834.1370330465

Running Iteration number= 14
Predicted values of y:
[[1.66401408e-65 9.89607039e-56 1.94422940e-53 ... 3.19233657e-54
  5.33290548e-35 8.48739836e-10]
 [1.66401408e-65 9.89607039e-56 1.94422940e-53 ... 3.19233657e-54
  5.33290548e-35 8.48739836e-10]
 [1.66401408e-65 9.89607039e-56 1.94422940e-53 ... 3.19233657e-54
  5.33290548e-35 8.48739836e-10]
 ...
 [1.66401408e-65 9.89607039e-56 1.94422940e-53 ... 3.19233657e-54
  5.33290548e-35 8.48739836e-10]
 [1.66401408e-65 9.89607039e-56 1.94422940e-53 ... 3.19233657e-54
  5.33290548e-35 8.48739836e-10]
 [1.66401408e-65 9.89607039e-56 1.94422940e-53 ... 3.19233657e-54
  5.33290548e-35 8.48739836e-10]]
Loss function= 1670395.2398733846

Running Iteration number= 15
Predicted values of y:
[[1.04815927e-56 1.06488629e-45 1.60860678e-44 ... 1.05376637e-44
  2.00691548e-26 1.00000000e+00]
 [1.04815927e-56 1.06488629e-45 1.60860678e-44 ... 1.05376637e-44
  2.00691548e-26 1.00000000e+00]
 [1.04815927e-56 1.06488629e

Loss function= 2120040.6155268745

Running Iteration number= 26
Predicted values of y:
[[1.06885799e-59 5.02245588e-28 3.02452514e-46 ... 7.48939475e-47
  1.16022347e-70 1.00000000e+00]
 [1.06885799e-59 5.02245588e-28 3.02452514e-46 ... 7.48939475e-47
  1.16022347e-70 1.00000000e+00]
 [1.06885799e-59 5.02245588e-28 3.02452514e-46 ... 7.48939475e-47
  1.16022347e-70 1.00000000e+00]
 ...
 [1.06885799e-59 5.02245588e-28 3.02452514e-46 ... 7.48939475e-47
  1.16022347e-70 1.00000000e+00]
 [1.06885799e-59 5.02245588e-28 3.02452514e-46 ... 7.48939475e-47
  1.16022347e-70 1.00000000e+00]
 [1.06885799e-59 5.02245588e-28 3.02452514e-46 ... 7.48939475e-47
  1.16022347e-70 1.00000000e+00]]
Loss function= 2101049.216049277

Running Iteration number= 27
Predicted values of y:
[[6.12141366e-45 4.91380624e-12 2.27520757e-31 ... 2.24772835e-31
  3.96979684e-56 2.00633098e-73]
 [6.12141366e-45 4.91380624e-12 2.27520757e-31 ... 2.24772835e-31
  3.96979684e-56 2.00633098e-73]
 [6.12141366e-45 4.91380624e-

Loss function= 1823086.9726912347

Running Iteration number= 38
Predicted values of y:
[[4.15747849e-44 9.01825145e-01 3.63263179e-33 ... 2.54840336e-81
  2.23482335e-55 1.33625105e-69]
 [4.15747849e-44 9.01825145e-01 3.63263179e-33 ... 2.54840336e-81
  2.23482335e-55 1.33625105e-69]
 [4.15747849e-44 9.01825145e-01 3.63263179e-33 ... 2.54840336e-81
  2.23482335e-55 1.33625105e-69]
 ...
 [4.15747849e-44 9.01825145e-01 3.63263179e-33 ... 2.54840336e-81
  2.23482335e-55 1.33625105e-69]
 [4.15747849e-44 9.01825145e-01 3.63263179e-33 ... 2.54840336e-81
  2.23482335e-55 1.33625105e-69]
 [4.15747849e-44 9.01825145e-01 3.63263179e-33 ... 2.54840336e-81
  2.23482335e-55 1.33625105e-69]]
Loss function= 2092348.730225069

Running Iteration number= 39
Predicted values of y:
[[2.54767600e-34 7.24693868e-69 2.92393469e-23 ... 8.18366292e-71
  8.18186477e-46 1.53164264e-59]
 [2.54767600e-34 7.24693868e-69 2.92393469e-23 ... 8.18366292e-71
  8.18186477e-46 1.53164264e-59]
 [2.54767600e-34 7.24693868e-

Loss function= 1910530.5304229318

Running Iteration number= 50
Predicted values of y:
[[4.33523111e-13 4.21466672e-34 9.99819772e-01 ... 1.58080859e-41
  4.82178262e-27 2.60616507e-35]
 [4.33523111e-13 4.21466672e-34 9.99819772e-01 ... 1.58080859e-41
  4.82178262e-27 2.60616507e-35]
 [4.33523111e-13 4.21466672e-34 9.99819772e-01 ... 1.58080859e-41
  4.82178262e-27 2.60616507e-35]
 ...
 [4.33523111e-13 4.21466672e-34 9.99819772e-01 ... 1.58080859e-41
  4.82178262e-27 2.60616507e-35]
 [4.33523111e-13 4.21466672e-34 9.99819772e-01 ... 1.58080859e-41
  4.82178262e-27 2.60616507e-35]
 [4.33523111e-13 4.21466672e-34 9.99819772e-01 ... 1.58080859e-41
  4.82178262e-27 2.60616507e-35]]
Loss function= 1389020.8317904451

Running Iteration number= 51
Predicted values of y:
[[1.14617079e-09 1.90357721e-29 6.74399971e-85 ... 2.19018978e-37
  7.61622249e-24 1.28882576e-31]
 [1.14617079e-09 1.90357721e-29 6.74399971e-85 ... 2.19018978e-37
  7.61622249e-24 1.28882576e-31]
 [1.14617079e-09 1.90357721e

Loss function= 1572608.4800980906

Running Iteration number= 62
Predicted values of y:
[[9.99999600e-01 3.98897995e-07 2.03239676e-72 ... 1.53133876e-20
  3.47261848e-17 1.12323210e-19]
 [9.99999600e-01 3.98897995e-07 2.03239676e-72 ... 1.53133876e-20
  3.47261848e-17 1.12323210e-19]
 [9.99999600e-01 3.98897995e-07 2.03239676e-72 ... 1.53133876e-20
  3.47261848e-17 1.12323210e-19]
 ...
 [9.99999600e-01 3.98897995e-07 2.03239676e-72 ... 1.53133876e-20
  3.47261848e-17 1.12323210e-19]
 [9.99999600e-01 3.98897995e-07 2.03239676e-72 ... 1.53133876e-20
  3.47261848e-17 1.12323210e-19]
 [9.99999600e-01 3.98897995e-07 2.03239676e-72 ... 1.53133876e-20
  3.47261848e-17 1.12323210e-19]]
Loss function= 1510972.852372631

Running Iteration number= 63
Predicted values of y:
[[2.74797945e-83 9.99677539e-01 3.91654841e-67 ... 1.17733364e-14
  3.04379139e-12 3.08239015e-14]
 [2.74797945e-83 9.99677539e-01 3.91654841e-67 ... 1.17733364e-14
  3.04379139e-12 3.08239015e-14]
 [2.74797945e-83 9.99677539e-

Loss function= 1830080.6729134615

Running Iteration number= 74
Predicted values of y:
[[1.29471278e-82 5.50782377e-17 3.80954118e-65 ... 9.26962896e-25
  2.57636254e-46 8.30576054e-17]
 [1.29471278e-82 5.50782377e-17 3.80954118e-65 ... 9.26962896e-25
  2.57636254e-46 8.30576054e-17]
 [1.29471278e-82 5.50782377e-17 3.80954118e-65 ... 9.26962896e-25
  2.57636254e-46 8.30576054e-17]
 ...
 [1.29471278e-82 5.50782377e-17 3.80954118e-65 ... 9.26962896e-25
  2.57636254e-46 8.30576054e-17]
 [1.29471278e-82 5.50782377e-17 3.80954118e-65 ... 9.26962896e-25
  2.57636254e-46 8.30576054e-17]
 [1.29471278e-82 5.50782377e-17 3.80954118e-65 ... 9.26962896e-25
  2.57636254e-46 8.30576054e-17]]
Loss function= 1948292.2698499514

Running Iteration number= 75
Predicted values of y:
[[1.18101314e-67 8.58284968e-01 4.56442495e-50 ... 4.43107422e-09
  1.40405197e-31 1.41715027e-01]
 [1.18101314e-67 8.58284968e-01 4.56442495e-50 ... 4.43107422e-09
  1.40405197e-31 1.41715027e-01]
 [1.18101314e-67 8.58284968e

Loss function= 1550760.2287468575

Running Iteration number= 86
Predicted values of y:
[[4.73960076e-21 4.49650087e-49 1.12153454e-36 ... 1.32483774e-78
  9.47058450e-24 1.00000000e+00]
 [4.73960076e-21 4.49650087e-49 1.12153454e-36 ... 1.32483774e-78
  9.47058450e-24 1.00000000e+00]
 [4.73960076e-21 4.49650087e-49 1.12153454e-36 ... 1.32483774e-78
  9.47058450e-24 1.00000000e+00]
 ...
 [4.73960076e-21 4.49650087e-49 1.12153454e-36 ... 1.32483774e-78
  9.47058450e-24 1.00000000e+00]
 [4.73960076e-21 4.49650087e-49 1.12153454e-36 ... 1.32483774e-78
  9.47058450e-24 1.00000000e+00]
 [4.73960076e-21 4.49650087e-49 1.12153454e-36 ... 1.32483774e-78
  9.47058450e-24 1.00000000e+00]]
Loss function= 1550557.7803180548

Running Iteration number= 87
Predicted values of y:
[[3.48209173e-10 5.64343211e-37 1.08228890e-25 ... 5.10066167e-67
  4.15690542e-13 2.57376746e-77]
 [3.48209173e-10 5.64343211e-37 1.08228890e-25 ... 5.10066167e-67
  4.15690542e-13 2.57376746e-77]
 [3.48209173e-10 5.64343211e

Loss function= 1979151.565130872

Running Iteration number= 98
Predicted values of y:
[[5.72279069e-13 2.90432408e-26 3.05603156e-27 ... 5.78527152e-62
  1.77310955e-18 2.55381397e-77]
 [5.72279069e-13 2.90432408e-26 3.05603156e-27 ... 5.78527152e-62
  1.77310955e-18 2.55381397e-77]
 [5.72279069e-13 2.90432408e-26 3.05603156e-27 ... 5.78527152e-62
  1.77310955e-18 2.55381397e-77]
 ...
 [5.72279069e-13 2.90432408e-26 3.05603156e-27 ... 5.78527152e-62
  1.77310955e-18 2.55381397e-77]
 [5.72279069e-13 2.90432408e-26 3.05603156e-27 ... 5.78527152e-62
  1.77310955e-18 2.55381397e-77]
 [5.72279069e-13 2.90432408e-26 3.05603156e-27 ... 5.78527152e-62
  1.77310955e-18 2.55381397e-77]]
Loss function= 1878563.459674325

Running Iteration number= 99
Predicted values of y:
[[9.99998149e-01 8.66975023e-13 7.01425054e-15 ... 5.29761582e-49
  1.85106562e-06 8.34710349e-65]
 [9.99998149e-01 8.66975023e-13 7.01425054e-15 ... 5.29761582e-49
  1.85106562e-06 8.34710349e-65]
 [9.99998149e-01 8.66975023e-1